server:
  port: 2000

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev # 表示开发环境
    #active: prod # 表示生产环境
    #active: test # 表示测试环境
#jwt配置
jwt:
  token:
    tokenExpiration: 43200 #有效时间,单位分钟
    tokenSignKey: jxMall  #当前程序签名秘钥 自定义
